version: "3"

services:
  back-office-app:
    build:
      context: ./back-office-app/
      target: development
    volumes:
      - ./back-office-app/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    command: npm run dev
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017
      - MONGODB_NAME=url_shortener
  
  public-app:
    build:
      context: ./public-app/
      target: development
    volumes:
      - ./public-app/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017
      - MONGODB_NAME=url_shortener
  
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - ./config/redis:/usr/local/etc/redis
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      # - REDIS_DATABASES=1
