version: "3"

services:
  back-office-app:
    build:
      context: ./back-office-app/
      target: development
    volumes:
      - ./back-office-app/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${BACK_OFFICE_APP_PORT}:${BACK_OFFICE_APP_PORT}
    command: npm run dev
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017
      - MONGODB_NAME=url_shortener
      - BACK_OFFICE_APP_PORT=${BACK_OFFICE_APP_PORT}
  
  public-app:
    build:
      context: ./public-app/
      target: development
    volumes:
      - ./public-app/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PUBLIC_APP_PORT}:${PUBLIC_APP_PORT}
    command: npm run dev
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    environment:
      - MONGODB_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017
      - MONGODB_NAME=url_shortener
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # - REDIS_PASSWORD=password
      # RABBIT VARIABLES
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=pass
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - PUBLIC_APP_PORT=${PUBLIC_APP_PORT}
  
  housekeeper-app:
    build:
      context: ./housekeeper-app/
      target: development
    volumes:
      - ./housekeeper-app/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${HOUSEKEEPER_APP_PORT}:${HOUSEKEEPER_APP_PORT}
    command: npm run dev
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - MONGODB_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017
      - MONGODB_NAME=url_shortener
      # RABBIT VARIABLES
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=pass
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - HOUSEKEEPER_APP_PORT=${HOUSEKEEPER_APP_PORT}

  seeder-app:
    build:
      context: ./seeder-app/
      target: development
    volumes:
      - ./seeder-app/:/usr/src/app
      - ./data/seeder/:/usr/src/app/data
      - /usr/src/app/node_modules
    ports:
      - ${SEEDER_APP_PORT}:${SEEDER_APP_PORT}
    command: npm run dev
    environment:
      - SEEDER_APP_PORT=${SEEDER_APP_PORT}

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - 6379:6379
    command: [redis-server, /usr/local/etc/redis.conf]
    volumes:
      - ./data/redis:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis.conf
    environment:
      # - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      # - REDIS_DATABASES=1

  rabbitmq:
      image: rabbitmq:3.12.12-management-alpine
      ports:
          - 5672:5672
          - 15672:15672
      environment:
          - RABBITMQ_DEFAULT_PASS=pass
          - RABBITMQ_DEFAULT_USER=user
      volumes:
          - ./data/rabbitmq/data/:/var/lib/rabbitmq/
          - ./data/rabbitmq/log/:/var/log/rabbitmq