services:
  back-office-app:
    build:
      context: ./back-office-app/
      target: production
    volumes:
      - ./back-office-app/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${BACK_OFFICE_APP_PORT}:${BACK_OFFICE_APP_PORT}
    depends_on:
      - mongodb
    environment:
    # mongo
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_NAME=${MONGODB_NAME}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
    # app
      - BACK_OFFICE_APP_PORT=${BACK_OFFICE_APP_PORT}
    # seeder
      - SEEDER_URL=http://seeder-app:${SEEDER_APP_PORT}
    # jwt
      - JWT_SECRET=${JWT_SECRET}
  
  public-app:
    build:
      context: ./public-app/
      target: production
    volumes:
      - ./public-app/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PUBLIC_APP_PORT}:${PUBLIC_APP_PORT}
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    environment:
    # mongo
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_NAME=${MONGODB_NAME}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
    # redis
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    # rabbit
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
    # app
      - PUBLIC_APP_PORT=${PUBLIC_APP_PORT}
  
  housekeeper-app:
    build:
      context: ./housekeeper-app/
      target: production
    volumes:
      - ./housekeeper-app/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${HOUSEKEEPER_APP_PORT}:${HOUSEKEEPER_APP_PORT}
    depends_on:
      - mongodb
      - rabbitmq
    environment:
    # mongo
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_NAME=${MONGODB_NAME}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
    # rabbit
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
    # app
      - HOUSEKEEPER_APP_PORT=${HOUSEKEEPER_APP_PORT}

  seeder-app:
    build:
      context: ./seeder-app/
      target: production
    volumes:
      - ./seeder-app/:/usr/src/app
      - ./data/seeder/:/usr/src/app/data
      - /usr/src/app/node_modules
    ports:
      - ${SEEDER_APP_PORT}:${SEEDER_APP_PORT}
    environment:
      - SEEDER_APP_PORT=${SEEDER_APP_PORT}

  mongodb:
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./data/mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: [redis-server, /usr/local/etc/redis.conf]
    volumes:
      - ./data/redis:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis.conf
    environment:
      - REDIS_PORT=${REDIS_PORT}

  rabbitmq:
      image: rabbitmq:3.12.12-management-alpine
      ports:
          - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
          - ${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}
      environment:
          - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
          - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      volumes:
          - ./data/rabbitmq/data/:/var/lib/rabbitmq/
          - ./data/rabbitmq/log/:/var/log/rabbitmq